### PR TITLE
update new menu_item config examples

### PR DESCRIPTION
**Pull request by charuwts**
## Summary

Updates 4.2 menu_item examples to match changes made here: https://github.com/solidusio/solidus/commit/c9e151ce276875d17e1013c61d272734f7b8ce90#diff-b9a08bd588c0052ee198e4df7b36adc56c099e2d77ee2bb100568ede58f32744R54-R63 

## Checklist

- [ ] I have followed the [Diátaxis](https://diataxis.fr/) framework in my PR.
  - Made a simple change, the pages that were edited are still pending `needs-diataxis-rewrite`
- [x] I have verified that the preview environment works correctly.

### CODE REVIEW

**Comment by charuwts** [comment]
Looks like this should be updated or removed as well since position will be deprecated in 5.0?

https://github.com/solidusio/edgeguides/blob/e5ac256c214e726177a2c88a2d8ffba6976fc090/versioned_docs/version-4.2/customization/customizing-the-backend.mdx#L306-L311

**Review by forkata — APPROVED** [review]
Thank you for this change @charuwts! This looks good to me.

**Comment by charuwts** [comment]
Hey there, Happy to help! Is there something more I need to do to get this merged?

**Review by kennyadsl — APPROVED** [review]
Thanks!

**Pull request merged**
