### PR TITLE
Update promotions system guide

### PR DESCRIPTION
**Pull request by seand7565**
Attempts to fix a few issues with the promotion system guide.

- [x] Add code titles to everything
- [x] Properly namespace models
- [x] Change StoreController to StoreControllerDecorator (won't work as a decorator without ending in `Decorator`)
- [x] Fix the admin view path (`backend/spree` -> `spree/admin`)
- [x] Use the correct text field form helper (`string_field_tag` -> `text_field_tag`)
- [x] Break out promotion action modules (to be consistent)
- [x] Add a `compute_amount` method to the promotion action (`adjustment.rb` expects this method to exist)
- [x] Add an empty html.erb file for promotion rule (Solidus will break when you add it otherwise, it expects a view)
- [x] Pass promotion code from handler to the payload
- [x] Persist promotion if order doesn't already exist

Still one logic issue to fix with this: 
If the user lands on the website with this promotion code in their URL, they will not have an order, so the promotion won't be applied. When the navigate somewhere, this code is removed from the URL. So there's no way currently for this promotion to be applied to new customers. Since this is just an example, I'm not sure how much we care... But it could be confusing if anyone actually tries to implement this (and hard to demonstrate on a screencast 😉 ) 

One potential solution, and the one I'll probably drop in, is to just create an order if one doesn't exist for the customer.

### CODE REVIEW

**Comment by seand7565** [comment]
Github isn't letting Github isn't letting me update the PR description right now, so I'll just post this here:

Promotion persisting: The guide now stores the promotion code ID in a cookie. I explain why in the guide, but essentially, the user likely won't have an order or shipment to apply the promotion to when they first land on your site, so you have the store the desired promotion code somewhere for future use.

**Comment by kennyadsl** [comment]
@seand7565 Hey! Is the logical issue described above solved now?

**Comment by seand7565** [comment]
@kennyadsl Yes! I'm using the cookies solution in the above comment. 🍪

**Comment by waiting-for-dev** [comment]
For context, that part has recently been revisited and updated to use a less contrived example.

**Pull request closed without merging**
