### PR TITLE
Move policies pages from solidus.io to guides

### PR DESCRIPTION
**Pull request by kennyadsl**
## Summary

It is almost a 1-1 copy from the solidus website repository, but I had to rewrite in JS the code that creates the supported versions table and check dynamically if a version is still supported or not (thanks for the help ChatGPT 🤖).

~When approved, I'll generate the corresponding pages for the 4.1 version for immediate availability.~ see https://github.com/solidusio/edgeguides/pull/120#issuecomment-1625543089

## Checklist

- [ ] I have followed the [Diátaxis](https://diataxis.fr/) framework in my PR.
- [ ] I have verified that the preview environment works correctly.

### CODE REVIEW

**Review by elia — APPROVED** [review]
LGTM 👍👍👍 

The only thing we could consider as an improvement is to keep the policy directory out of versioning, given its contents are not tied to specific versions.

But that can be done as a follow up too.

**Comment by kennyadsl** [comment]
@elia Oh, I didn't know that was possible, giving it a shot, thanks!

**Review by waiting-for-dev — APPROVED** [review]
Thanks!!!

**Review by rainerdema — APPROVED** [review]
👍

**Pull request merged**
